#!/bin/bash
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "HHHHHHHHH     HHHHHHHHH                   lllllll lllllll                                                                                                                               ";
echo "H:::::::H     H:::::::H                   l:::::l l:::::l                                                                                                                               ";
echo "H:::::::H     H:::::::H                   l:::::l l:::::l                                                                                                                               ";
echo "HH::::::H     H::::::HH                   l:::::l l:::::l                                                                                                                               ";
echo "  H:::::H     H:::::H      eeeeeeeeeeee    l::::l  l::::l    ooooooooooo                                                                                                                ";
echo "  H:::::H     H:::::H    ee::::::::::::ee  l::::l  l::::l  oo:::::::::::oo                                                                                                              ";
echo "  H::::::HHHHH::::::H   e::::::eeeee:::::eel::::l  l::::l o:::::::::::::::o                                                                                                             ";
echo "  H:::::::::::::::::H  e::::::e     e:::::el::::l  l::::l o:::::ooooo:::::o                                                                                                             ";
echo "  H:::::::::::::::::H  e:::::::eeeee::::::el::::l  l::::l o::::o     o::::o                                                                                                             ";
echo "  H::::::HHHHH::::::H  e:::::::::::::::::e l::::l  l::::l o::::o     o::::o                                                                                                             ";
echo "  H:::::H     H:::::H  e::::::eeeeeeeeeee  l::::l  l::::l o::::o     o::::o                                                                                                             ";
echo "  H:::::H     H:::::H  e:::::::e           l::::l  l::::l o::::o     o::::o                                                                                                             ";
echo "HH::::::H     H::::::HHe::::::::e         l::::::ll::::::lo:::::ooooo:::::o                                                                                                             ";
echo "H:::::::H     H:::::::H e::::::::eeeeeeee l::::::ll::::::lo:::::::::::::::o                                                                                                             ";
echo "H:::::::H     H:::::::H  ee:::::::::::::e l::::::ll::::::l oo:::::::::::oo                                                                                                              ";
echo "HHHHHHHHH     HHHHHHHHH    eeeeeeeeeeeeee llllllllllllllll   ooooooooooo                                                                                                                ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "        GGGGGGGGGGGGG                                       ffffffffffffffff                                                            CCCCCCCCCCCCC                                   ";
echo "     GGG::::::::::::G                                      f::::::::::::::::f                                                        CCC::::::::::::C                                   ";
echo "   GG:::::::::::::::G                                     f::::::::::::::::::f                                                     CC:::::::::::::::C                                   ";
echo "  G:::::GGGGGGGG::::G                                     f::::::fffffff:::::f                                                    C:::::CCCCCCCC::::C                                   ";
echo " G:::::G       GGGGGGrrrrr   rrrrrrrrr   aaaaaaaaaaaaa    f:::::f       ffffffaaaaaaaaaaaaa  nnnn  nnnnnnnn      aaaaaaaaaaaaa   C:::::C       CCCCCC   ooooooooooo   nnnn  nnnnnnnn    ";
echo "G:::::G              r::::rrr:::::::::r  a::::::::::::a   f:::::f             a::::::::::::a n:::nn::::::::nn    a::::::::::::a C:::::C               oo:::::::::::oo n:::nn::::::::nn  ";
echo "G:::::G              r:::::::::::::::::r aaaaaaaaa:::::a f:::::::ffffff       aaaaaaaaa:::::an::::::::::::::nn   aaaaaaaaa:::::aC:::::C              o:::::::::::::::on::::::::::::::nn ";
echo "G:::::G    GGGGGGGGGGrr::::::rrrrr::::::r         a::::a f::::::::::::f                a::::ann:::::::::::::::n           a::::aC:::::C              o:::::ooooo:::::onn:::::::::::::::n";
echo "G:::::G    G::::::::G r:::::r     r:::::r  aaaaaaa:::::a f::::::::::::f         aaaaaaa:::::a  n:::::nnnn:::::n    aaaaaaa:::::aC:::::C              o::::o     o::::o  n:::::nnnn:::::n";
echo "G:::::G    GGGGG::::G r:::::r     rrrrrrraa::::::::::::a f:::::::ffffff       aa::::::::::::a  n::::n    n::::n  aa::::::::::::aC:::::C              o::::o     o::::o  n::::n    n::::n";
echo "G:::::G        G::::G r:::::r           a::::aaaa::::::a  f:::::f            a::::aaaa::::::a  n::::n    n::::n a::::aaaa::::::aC:::::C              o::::o     o::::o  n::::n    n::::n";
echo " G:::::G       G::::G r:::::r          a::::a    a:::::a  f:::::f           a::::a    a:::::a  n::::n    n::::na::::a    a:::::a C:::::C       CCCCCCo::::o     o::::o  n::::n    n::::n";
echo "  G:::::GGGGGGGG::::G r:::::r          a::::a    a:::::a f:::::::f          a::::a    a:::::a  n::::n    n::::na::::a    a:::::a  C:::::CCCCCCCC::::Co:::::ooooo:::::o  n::::n    n::::n";
echo "   GG:::::::::::::::G r:::::r          a:::::aaaa::::::a f:::::::f          a:::::aaaa::::::a  n::::n    n::::na:::::aaaa::::::a   CC:::::::::::::::Co:::::::::::::::o  n::::n    n::::n";
echo "     GGG::::::GGG:::G r:::::r           a::::::::::aa:::af:::::::f           a::::::::::aa:::a n::::n    n::::n a::::::::::aa:::a    CCC::::::::::::C oo:::::::::::oo   n::::n    n::::n";
echo "        GGGGGG   GGGG rrrrrrr            aaaaaaaaaa  aaaafffffffff            aaaaaaaaaa  aaaa nnnnnn    nnnnnn  aaaaaaaaaa  aaaa       CCCCCCCCCCCCC   ooooooooooo     nnnnnn    nnnnnn";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
echo "                                                                                                                                                                                        ";
